"""
OpenEmotion Self-Model Module

自我模型的正式本体模块。
"""

from .model import (
    Capability,
    CapabilityLevel,
    FORMAL_OWNER_SCHEMA_VERSION,
    Goal,
    GoalStatus,
    Limitation,
    PHASE1_ALLOWED_PROOF_LEVERS,
    PHASE1_AUTHORITATIVE_FIELDS,
    PHASE1_LEGACY_REFERENCE_ONLY_FIELDS,
    Priority,
    RUNTIME_LOCAL_PROJECTION_FIELD,
    RUNTIME_LOCAL_PROJECTION_SEMANTICS,
    SelfModel,
    StandingCommitment,
    create_default_self_model,
)
from .governance import (
    ALLOW_WRITEBACK,
    HOLD_FOR_REVIEW,
    REJECT,
    ROLLBACK_TO_LAST_STABLE,
    ALLOWED_UPDATE_MODES,
    EVOLVABLE_FIELDS,
    HARD_INVARIANT_FIELDS,
    STABLE_DEFAULT_FIELDS,
    WRITABLE_AUTHORITATIVE_FIELDS,
    DriftAssessment,
    InvariantViolation,
    SelfModelUpdateDecision,
    SelfModelUpdateRequest,
    SelfModelWritebackResult,
    apply_governed_writeback,
    assess_drift,
    check_identity_invariants,
    evaluate_update_request,
)
from .replay import SelfModelReplay, SelfModelReplayResult
from .store import (
    DEFAULT_OWNER_ARTIFACTS_DIR,
    REQUIRED_REVISION_FIELDS,
    SelfModelReplayError,
    SelfModelRevisionRecord,
    SelfModelRevision,
    SelfModelStore,
)

__all__ = [
    "SelfModel",
    "Capability",
    "Limitation",
    "Goal",
    "StandingCommitment",
    "CapabilityLevel",
    "GoalStatus",
    "Priority",
    "FORMAL_OWNER_SCHEMA_VERSION",
    "PHASE1_AUTHORITATIVE_FIELDS",
    "PHASE1_ALLOWED_PROOF_LEVERS",
    "PHASE1_LEGACY_REFERENCE_ONLY_FIELDS",
    "RUNTIME_LOCAL_PROJECTION_FIELD",
    "RUNTIME_LOCAL_PROJECTION_SEMANTICS",
    "ALLOW_WRITEBACK",
    "HOLD_FOR_REVIEW",
    "REJECT",
    "ROLLBACK_TO_LAST_STABLE",
    "ALLOWED_UPDATE_MODES",
    "WRITABLE_AUTHORITATIVE_FIELDS",
    "HARD_INVARIANT_FIELDS",
    "STABLE_DEFAULT_FIELDS",
    "EVOLVABLE_FIELDS",
    "InvariantViolation",
    "DriftAssessment",
    "SelfModelUpdateRequest",
    "SelfModelUpdateDecision",
    "SelfModelWritebackResult",
    "check_identity_invariants",
    "assess_drift",
    "evaluate_update_request",
    "apply_governed_writeback",
    "DEFAULT_OWNER_ARTIFACTS_DIR",
    "REQUIRED_REVISION_FIELDS",
    "SelfModelReplayError",
    "SelfModelRevision",
    "SelfModelStore",
    "SelfModelRevisionRecord",
    "SelfModelReplay",
    "SelfModelReplayResult",
    "create_default_self_model",
]
