#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from program_state_common import (
    EGOCORE_PROGRAM_STATE_MIRROR,
    EVIDENCE_LEDGER_INDEX_PATH,
    OPENEMOTION_PROGRAM_STATE_MIRROR,
    PROGRAM_STATE_PATH,
    STATUS_MD_PATH,
    SUMMARY_MD_PATH,
    load_yaml,
    render_state_yaml_with_header,
    render_status_markdown,
    render_summary_markdown,
)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    program_state = load_yaml(PROGRAM_STATE_PATH)
    evidence_index = load_yaml(EVIDENCE_LEDGER_INDEX_PATH)

    _write(STATUS_MD_PATH, render_status_markdown(program_state, evidence_index))
    _write(SUMMARY_MD_PATH, render_summary_markdown(program_state, evidence_index))

    mirror_header = (
        "# AUTO-GENERATED COMPATIBILITY MIRROR\n"
        "# Source of truth: docs/PROGRAM_STATE_UNIFIED.yaml\n"
        "# Do not edit this file by hand. Edit docs/PROGRAM_STATE_UNIFIED.yaml and regenerate derived views.\n"
    )
    mirror_yaml = render_state_yaml_with_header(program_state, header=mirror_header)
    _write(EGOCORE_PROGRAM_STATE_MIRROR, mirror_yaml)
    _write(OPENEMOTION_PROGRAM_STATE_MIRROR, mirror_yaml)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
