#!/usr/bin/env python
"""
MVP15 Artifact Quality Assessment

Assesses the quality of reflection artifacts generated by MVP15.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field


@dataclass
class ArtifactStats:
    """Statistics for a single artifact."""
    filename: str
    size_bytes: int
    is_empty: bool
    has_content: bool
    content_preview: str
    unique_keys: List[str]
    duplicate_patterns: List[str]


@dataclass
class QualityReport:
    """Overall quality report."""
    total_artifacts: int = 0
    empty_count: int = 0
    empty_rate: float = 0.0
    total_size_bytes: int = 0
    avg_size_bytes: float = 0.0
    duplicate_rate: float = 0.0
    unique_key_coverage: Dict[str, float] = field(default_factory=dict)
    information_gain_score: float = 0.0
    recommendations: List[str] = field(default_factory=list)


def assess_artifact(file_path: Path) -> ArtifactStats:
    """Assess a single artifact file."""
    stat = file_path.stat()
    size_bytes = stat.st_size
    is_empty = size_bytes == 0
    
    content_preview = ""
    has_content = False
    unique_keys = []
    duplicate_patterns = []
    
    if not is_empty and file_path.suffix == ".json":
        try:
            with open(file_path) as f:
                data = json.load(f)
            has_content = True
            unique_keys = list(data.keys())
            content_preview = json.dumps(data)[:200]
            
            # Check for duplicate patterns
            content_str = json.dumps(data)
            for key in unique_keys:
                count = content_str.count(f'"{key}"')
                if count > 1:
                    duplicate_patterns.append(key)
        except Exception:
            pass
    
    return ArtifactStats(
        filename=file_path.name,
        size_bytes=size_bytes,
        is_empty=is_empty,
        has_content=has_content,
        content_preview=content_preview,
        unique_keys=unique_keys,
        duplicate_patterns=duplicate_patterns,
    )


def compute_quality_report(artifacts_dir: Path) -> QualityReport:
    """Compute overall quality report."""
    report = QualityReport()
    
    if not artifacts_dir.exists():
        report.recommendations.append("Artifacts directory does not exist")
        return report
    
    # Find all artifact files
    artifact_files = list(artifacts_dir.glob("*.json"))
    if not artifact_files:
        artifact_files = list(artifacts_dir.glob("*"))
    
    if not artifact_files:
        report.recommendations.append("No artifacts found")
        return report
    
    # Assess each artifact
    stats = []
    for f in artifact_files:
        if f.is_file():
            stat = assess_artifact(f)
            stats.append(stat)
    
    report.total_artifacts = len(stats)
    report.empty_count = sum(1 for s in stats if s.is_empty)
    report.empty_rate = report.empty_count / max(1, report.total_artifacts)
    report.total_size_bytes = sum(s.size_bytes for s in stats)
    report.avg_size_bytes = report.total_size_bytes / max(1, report.total_artifacts)
    
    # Duplicate rate
    all_duplicates = []
    for s in stats:
        all_duplicates.extend(s.duplicate_patterns)
    unique_duplicates = set(all_duplicates)
    report.duplicate_rate = len(unique_duplicates) / max(1, report.total_artifacts)
    
    # Key coverage
    all_keys = []
    for s in stats:
        all_keys.extend(s.unique_keys)
    key_counts = {}
    for k in all_keys:
        key_counts[k] = key_counts.get(k, 0) + 1
    
    for key, count in key_counts.items():
        report.unique_key_coverage[key] = count / max(1, report.total_artifacts)
    
    # Information gain score (simplified)
    # Based on: non-empty rate + unique keys / 10
    non_empty_rate = 1 - report.empty_rate
    unique_key_score = len(report.unique_key_coverage) / 10
    report.information_gain_score = min(1.0, non_empty_rate * 0.7 + unique_key_score * 0.3)
    
    # Recommendations
    if report.empty_rate > 0.5:
        report.recommendations.append("High empty rate - check generation logic")
    if report.avg_size_bytes < 100:
        report.recommendations.append("Small artifact size - may lack useful information")
    if report.information_gain_score < 0.5:
        report.recommendations.append("Low information gain - improve content generation")
    
    return report


def print_report(report: QualityReport):
    """Print the quality report."""
    print("=== MVP15 Artifact Quality Assessment ===")
    print(f"\n1. Artifact Counts:")
    print(f"   Total: {report.total_artifacts}")
    print(f"   Empty: {report.empty_count} ({report.empty_rate:.1%})")
    print(f"   Non-empty: {report.total_artifacts - report.empty_count}")
    
    print(f"\n2. Size Statistics:")
    print(f"   Total size: {report.total_size_bytes:,} bytes")
    print(f"   Average size: {report.avg_size_bytes:.1f} bytes")
    
    print(f"\n3. Quality Metrics:")
    print(f"   Empty rate: {report.empty_rate:.1%}")
    print(f"   Duplicate rate: {report.duplicate_rate:.1%}")
    print(f"   Information gain score: {report.information_gain_score:.2f}")
    
    print(f"\n4. Key Coverage:")
    if report.unique_key_coverage:
        for key, coverage in sorted(report.unique_key_coverage.items(), key=lambda x: x[1], reverse=True)[:10]:
            print(f"   {key}: {coverage:.1%}")
    else:
        print("   No keys found")
    
    print(f"\n5. Recommendations:")
    if report.recommendations:
        for rec in report.recommendations:
            print(f"   - {rec}")
    else:
        print("   - Quality acceptable")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir", type=str, default="artifacts/mvp15")
    parser.add_argument("--output", type=str, default="artifacts/mvp15/quality_report.json")
    args = parser.parse_args()
    
    artifacts_dir = Path(args.dir)
    report = compute_quality_report(artifacts_dir)
    print_report(report)
    
    # Save report
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w") as f:
        json.dump({
            "total_artifacts": report.total_artifacts,
            "empty_count": report.empty_count,
            "empty_rate": report.empty_rate,
            "total_size_bytes": report.total_size_bytes,
            "avg_size_bytes": report.avg_size_bytes,
            "duplicate_rate": report.duplicate_rate,
            "information_gain_score": report.information_gain_score,
            "unique_key_coverage": report.unique_key_coverage,
            "recommendations": report.recommendations,
        }, f, indent=2)
    
    print(f"\nReport saved to {output_path}")
