"""
MVP12 Candidate Evaluator

Scores and ranks candidates generated by the developmental core.
All evaluations are sandboxed and must go through Governor v2.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from .models import Candidate, CandidateType


@dataclass
class EvaluationResult:
    """Result of evaluating a candidate."""

    candidate_id: str
    score: float
    reasons: List[str]
    flags: List[str]
    approved_for_pool: bool


class CandidateEvaluator:
    """
    Evaluates and ranks candidates for the candidate pool.

    This is a sandboxed operation - evaluations are recommendations only.
    Final approval must come from Governor v2.
    """

    def __init__(
        self,
        confidence_weight: float = 0.4,
        relevance_weight: float = 0.3,
        risk_weight: float = 0.3,
    ):
        self.confidence_weight = confidence_weight
        self.relevance_weight = relevance_weight
        self.risk_weight = risk_weight

    def evaluate(
        self,
        candidate: Candidate,
        context: Optional[Dict[str, Any]] = None,
    ) -> EvaluationResult:
        """Evaluate a single candidate."""
        reasons = []
        flags = []

        # Base score from confidence
        score = candidate.confidence * self.confidence_weight
        reasons.append(f"Confidence: {candidate.confidence:.2f}")

        # Type-specific scoring
        if candidate.candidate_type == CandidateType.ACTION:
            action_score = self._evaluate_action(candidate, flags)
            score += action_score * self.relevance_weight
            reasons.append(f"Action score: {action_score:.2f}")

        elif candidate.candidate_type == CandidateType.INTERPRETATION:
            interp_score = self._evaluate_interpretation(candidate, flags)
            score += interp_score * self.relevance_weight
            reasons.append(f"Interpretation score: {interp_score:.2f}")

        elif candidate.candidate_type == CandidateType.EXPLANATION:
            expl_score = self._evaluate_explanation(candidate, flags)
            score += expl_score * self.relevance_weight
            reasons.append(f"Explanation score: {expl_score:.2f}")

        elif candidate.candidate_type == CandidateType.SELF_MODEL_HYPOTHESIS:
            hypo_score = self._evaluate_self_model_hypothesis(candidate, flags)
            score += hypo_score * self.relevance_weight
            reasons.append(f"Hypothesis score: {hypo_score:.2f}")

        # Risk assessment
        risk_score = self._assess_risk(candidate, flags)
        score -= risk_score * self.risk_weight
        if risk_score > 0:
            reasons.append(f"Risk penalty: {risk_score:.2f}")

        # Approval threshold
        approved = score >= 0.3 and len([f for f in flags if "critical" in f.lower()]) == 0

        return EvaluationResult(
            candidate_id=candidate.id,
            score=score,
            reasons=reasons,
            flags=flags,
            approved_for_pool=approved,
        )

    def evaluate_batch(
        self,
        candidates: List[Candidate],
        context: Optional[Dict[str, Any]] = None,
    ) -> List[EvaluationResult]:
        """Evaluate multiple candidates and return ranked results."""
        results = [self.evaluate(c, context) for c in candidates]
        results.sort(key=lambda r: r.score, reverse=True)
        return results

    def _evaluate_action(
        self,
        candidate: Candidate,
        flags: List[str],
    ) -> float:
        """Evaluate an action candidate."""
        score = 0.5

        # Check risk assessment
        risk = getattr(candidate, "risk_assessment", {}) or {}
        if risk:
            max_risk = max(risk.values()) if risk else 0
            if max_risk > 0.5:
                flags.append("High risk action")
                score -= 0.2

        # Check expected outcome
        expected = getattr(candidate, "expected_outcome", "") or ""
        if expected:
            score += 0.2

        return min(1.0, max(0.0, score))

    def _evaluate_interpretation(
        self,
        candidate: Candidate,
        flags: List[str],
    ) -> float:
        """Evaluate an interpretation candidate."""
        score = 0.5

        # Check alternatives
        alts = getattr(candidate, "alternatives", []) or []
        if alts:
            score += 0.1  # Good to consider alternatives

        # Check evidence
        evidence = getattr(candidate, "evidence_refs", []) or []
        if evidence:
            score += 0.2

        return min(1.0, max(0.0, score))

    def _evaluate_explanation(
        self,
        candidate: Candidate,
        flags: List[str],
    ) -> float:
        """Evaluate an explanation candidate."""
        score = 0.5

        # Check supporting facts
        facts = getattr(candidate, "supporting_facts", []) or []
        if facts:
            score += 0.2

        # Check counter evidence
        counter = getattr(candidate, "counter_evidence", []) or []
        if counter:
            score += 0.1  # Good to acknowledge counter evidence

        return min(1.0, max(0.0, score))

    def _evaluate_self_model_hypothesis(
        self,
        candidate: Candidate,
        flags: List[str],
    ) -> float:
        """Evaluate a self-model hypothesis."""
        score = 0.5

        # Check testability
        predictions = getattr(candidate, "test_predictions", []) or []
        if predictions:
            score += 0.2

        # Check falsifiability
        disconfirm = getattr(candidate, "disconfirmation_criteria", []) or []
        if disconfirm:
            score += 0.2

        return min(1.0, max(0.0, score))

    def _assess_risk(
        self,
        candidate: Candidate,
        flags: List[str],
    ) -> float:
        """Assess overall risk of a candidate."""
        risk = 0.0

        # Check metadata for risk indicators
        metadata = candidate.metadata or {}
        if metadata.get("high_impact"):
            risk += 0.3
            flags.append("High impact candidate")

        # Check content for risky patterns
        content = candidate.content or {}
        if content.get("affects_external"):
            risk += 0.2
            flags.append("Affects external systems")

        return min(1.0, risk)
