"""
MVP12 Developmental Core Models

Defines candidate types and cycle structures for the developmental core sandbox.
All candidates must be traceable and replayable.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class CandidateType(str, Enum):
    INTERPRETATION = "interpretation"
    ACTION = "action"
    EXPLANATION = "explanation"
    SELF_MODEL_HYPOTHESIS = "self_model_hypothesis"


class CycleTrigger(str, Enum):
    IDLE = "idle"
    UNRESOLVED_TENSION = "unresolved_tension"
    LONG_TERM_GOAL = "long_term_goal"
    REPLAY_EVENT = "replay_event"


@dataclass
class Candidate:
    """Base class for all candidates generated by the developmental core."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    candidate_type: CandidateType = CandidateType.INTERPRETATION
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    origin_cycle: str = ""
    confidence: float = 0.5
    trace_reference: str = ""
    content: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["candidate_type"] = self.candidate_type.value
        return data

    def compute_hash(self) -> str:
        """Compute deterministic hash for replay verification."""
        data = self.to_dict()
        data.pop("id", None)  # Exclude ID for deterministic hashing
        data.pop("timestamp", None)  # Exclude timestamp
        return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]


@dataclass
class InterpretationCandidate(Candidate):
    """Candidate interpretation of an event or situation."""

    candidate_type: CandidateType = CandidateType.INTERPRETATION
    interpretation: str = ""
    evidence_refs: List[str] = field(default_factory=list)
    alternatives: List[str] = field(default_factory=list)


@dataclass
class ActionCandidate(Candidate):
    """Candidate action proposal."""

    candidate_type: CandidateType = CandidateType.ACTION
    action_type: str = ""
    target: str = ""
    expected_outcome: str = ""
    risk_assessment: Dict[str, float] = field(default_factory=dict)


@dataclass
class ExplanationCandidate(Candidate):
    """Candidate explanation for internal state or behavior."""

    candidate_type: CandidateType = CandidateType.EXPLANATION
    explanation: str = ""
    supporting_facts: List[str] = field(default_factory=list)
    counter_evidence: List[str] = field(default_factory=list)


@dataclass
class SelfModelHypothesis(Candidate):
    """Candidate hypothesis about the self model."""

    candidate_type: CandidateType = CandidateType.SELF_MODEL_HYPOTHESIS
    hypothesis: str = ""
    test_predictions: List[str] = field(default_factory=list)
    disconfirmation_criteria: List[str] = field(default_factory=list)


@dataclass
class CycleContext:
    """Context for a developmental cycle."""

    cycle_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    seed: int = 0
    trigger: CycleTrigger = CycleTrigger.IDLE
    started_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    parent_cycle: Optional[str] = None
    state_snapshot: Dict[str, Any] = field(default_factory=dict)
    trace_hash: str = ""

    def compute_trace_hash(self) -> str:
        """Compute deterministic trace hash for replay verification."""
        data = {
            "seed": self.seed,
            "trigger": self.trigger.value,
            "parent_cycle": self.parent_cycle,
            "state_snapshot": self.state_snapshot,
        }
        return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]

    def __post_init__(self):
        if not self.trace_hash:
            self.trace_hash = self.compute_trace_hash()


@dataclass
class CycleResult:
    """Result of a completed developmental cycle."""

    context: CycleContext
    candidates: List[Candidate] = field(default_factory=list)
    completed_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    success: bool = True
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "cycle_id": self.context.cycle_id,
            "seed": self.context.seed,
            "trigger": self.context.trigger.value,
            "trace_hash": self.context.trace_hash,
            "candidates": [c.to_dict() for c in self.candidates],
            "completed_at": self.completed_at,
            "success": self.success,
            "error": self.error,
        }
