"""
MVP-10 T04-T05: Workspace Module

T04: Candidate API
- Candidate dataclass: source, type, utility, risk, cost, evidence, rationale, payload
- CandidatePool: add, remove, sort, dedupe, merge
- Support comparison and sorting

T05: Arbitrator
- Arbitrator class: select focus from candidates
- Only one chosen_focus per tick
- Write rationale for selection
- Broadcast mechanism

MVP11-T05: Homeostasis Workspace Integration
- HomeostasisManager integration
- Homeostasis-driven candidates (rest, simplify, seek_info, defer)
- Homeostasis signal in arbitration scoring
- Feature flag: ENABLE_HOMEOSTASIS
"""
import time
import hashlib
from typing import Any, Dict, List, Optional, Set
from dataclasses import dataclass, field
from enum import Enum

# MVP11-T05: Import HomeostasisManager
from emotiond.homeostasis import HomeostasisManager, HomeostasisState


# Feature flag for homeostasis integration
ENABLE_HOMEOSTASIS = True  # Default: True


class CandidateType(Enum):
    """Types of workspace candidates."""
    INTENT = "intent"
    GOAL = "goal"
    ACTION = "action"
    REFLECTION = "reflection"
    INFO_SEEK = "info_seek"
    RECOVERY = "recovery"
    # MVP11-T05: New candidate types for homeostasis
    REST = "rest"
    SIMPLIFY = "simplify"
    DEFER = "defer"


@dataclass
class Candidate:
    """
    T04: A candidate intent/focus considered during decision.
    
    Candidates are generated by various modules and compete for
    the system's focus during workspace arbitration.
    
    Attributes:
        source: Module/component that generated this candidate
        type: Type of candidate (intent, goal, action, etc.)
        utility: Expected utility score (0.0 to 1.0)
        risk: Risk level (0.0 to 1.0)
        cost: Estimated cost (0.0 to 1.0)
        evidence: Supporting evidence for this candidate
        rationale: Explanation for why this candidate was generated
        payload: Additional data needed for execution
    """
    id: str
    source: str
    type: CandidateType
    utility: float = 0.5
    risk: float = 0.0
    cost: float = 0.0
    evidence: List[Dict[str, Any]] = field(default_factory=list)
    rationale: str = ""
    payload: Dict[str, Any] = field(default_factory=dict)
    ts: float = field(default_factory=time.time)
    
    def __post_init__(self):
        """Validate and clamp values."""
        self.utility = max(0.0, min(1.0, self.utility))
        self.risk = max(0.0, min(1.0, self.risk))
        self.cost = max(0.0, min(1.0, self.cost))
        
        # Auto-generate ID if not provided
        if not self.id:
            content = f"{self.source}:{self.type.value}:{time.time()}"
            self.id = hashlib.md5(content.encode()).hexdigest()[:8]
    
    def compute_score(self) -> float:
        """
        Compute overall score considering utility, risk, and cost.
        
        Score = utility - (risk * 0.5) - (cost * 0.3)
        """
        return self.utility - (self.risk * 0.5) - (self.cost * 0.3)
    
    def __lt__(self, other: "Candidate") -> bool:
        """Compare by computed score."""
        return self.compute_score() < other.compute_score()
    
    def __le__(self, other: "Candidate") -> bool:
        """Compare by computed score."""
        return self.compute_score() <= other.compute_score()
    
    def __gt__(self, other: "Candidate") -> bool:
        """Compare by computed score."""
        return self.compute_score() > other.compute_score()
    
    def __ge__(self, other: "Candidate") -> bool:
        """Compare by computed score."""
        return self.compute_score() >= other.compute_score()
    
    def __eq__(self, other: object) -> bool:
        """Compare by ID."""
        if not isinstance(other, Candidate):
            return False
        return self.id == other.id
    
    def __hash__(self) -> int:
        """Hash by ID."""
        return hash(self.id)
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "id": self.id,
            "source": self.source,
            "type": self.type.value,
            "utility": round(self.utility, 4),
            "risk": round(self.risk, 4),
            "cost": round(self.cost, 4),
            "evidence": self.evidence,
            "rationale": self.rationale,
            "payload": self.payload,
            "score": round(self.compute_score(), 4),
            "ts": self.ts,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Candidate":
        """Deserialize from dictionary."""
        return cls(
            id=data.get("id", ""),
            source=data.get("source", "unknown"),
            type=CandidateType(data.get("type", "intent")),
            utility=data.get("utility", 0.5),
            risk=data.get("risk", 0.0),
            cost=data.get("cost", 0.0),
            evidence=data.get("evidence", []),
            rationale=data.get("rationale", ""),
            payload=data.get("payload", {}),
            ts=data.get("ts", time.time()),
        )


@dataclass
class CandidatePool:
    """
    T04: Pool of candidates for workspace arbitration.
    
    Provides operations for managing candidate collections:
    - add: Add new candidates
    - remove: Remove by ID or criteria
    - sort: Sort by score or custom criteria
    - dedupe: Remove duplicates
    - merge: Combine with another pool
    
    MVP11-T05: Added homeostasis-driven candidate generation
    """
    candidates: List[Candidate] = field(default_factory=list)
    max_size: int = 100
    _id_set: Set[str] = field(default_factory=set, repr=False)
    
    def __post_init__(self):
        """Initialize ID set from candidates."""
        self._id_set = {c.id for c in self.candidates}
    
    def add(self, candidate: Candidate) -> bool:
        """
        Add a candidate to the pool.
        
        Args:
            candidate: Candidate to add
        
        Returns:
            True if added, False if duplicate or pool full
        """
        if candidate.id in self._id_set:
            return False
        
        if len(self.candidates) >= self.max_size:
            # Remove lowest-scored candidate
            self.sort(reverse=True)
            removed = self.candidates.pop()
            self._id_set.discard(removed.id)
        
        self.candidates.append(candidate)
        self._id_set.add(candidate.id)
        return True
    
    def remove(self, candidate_id: str) -> Optional[Candidate]:
        """
        Remove a candidate by ID.
        
        Args:
            candidate_id: ID of candidate to remove
        
        Returns:
            Removed candidate or None if not found
        """
        for i, c in enumerate(self.candidates):
            if c.id == candidate_id:
                removed = self.candidates.pop(i)
                self._id_set.discard(candidate_id)
                return removed
        return None
    
    def remove_by_source(self, source: str) -> List[Candidate]:
        """
        Remove all candidates from a specific source.
        
        Args:
            source: Source identifier
        
        Returns:
            List of removed candidates
        """
        removed = []
        remaining = []
        
        for c in self.candidates:
            if c.source == source:
                removed.append(c)
                self._id_set.discard(c.id)
            else:
                remaining.append(c)
        
        self.candidates = remaining
        return removed
    
    def sort(self, reverse: bool = True) -> None:
        """
        Sort candidates by computed score.
        
        Args:
            reverse: If True, highest scores first
        """
        self.candidates.sort(reverse=reverse)
    
    def dedupe(self) -> int:
        """
        Remove duplicate candidates (by ID).
        
        Returns:
            Number of duplicates removed
        """
        seen = set()
        unique = []
        removed_count = 0
        
        for c in self.candidates:
            if c.id not in seen:
                seen.add(c.id)
                unique.append(c)
            else:
                removed_count += 1
        
        self.candidates = unique
        self._id_set = seen
        return removed_count
    
    def merge(self, other: "CandidatePool") -> int:
        """
        Merge another pool into this one.
        
        Args:
            other: Pool to merge
        
        Returns:
            Number of candidates added
        """
        added = 0
        for c in other.candidates:
            if self.add(c):
                added += 1
        return added
    
    def get_best(self) -> Optional[Candidate]:
        """Get the highest-scored candidate."""
        if not self.candidates:
            return None
        return max(self.candidates, key=lambda c: c.compute_score())
    
    def get_by_id(self, candidate_id: str) -> Optional[Candidate]:
        """Get a candidate by ID."""
        for c in self.candidates:
            if c.id == candidate_id:
                return c
        return None
    
    def get_by_type(self, candidate_type: CandidateType) -> List[Candidate]:
        """Get all candidates of a specific type."""
        return [c for c in self.candidates if c.type == candidate_type]
    
    def get_by_source(self, source: str) -> List[Candidate]:
        """Get all candidates from a specific source."""
        return [c for c in self.candidates if c.source == source]
    
    def filter_by_score(self, min_score: float = 0.0) -> List[Candidate]:
        """Get candidates above minimum score."""
        return [c for c in self.candidates if c.compute_score() >= min_score]
    
    # MVP11-T05: Homeostasis-driven candidate generation
    def add_homeostasis_candidates(
        self,
        homeostasis_manager: HomeostasisManager,
        stress_threshold: float = 0.3
    ) -> List[Candidate]:
        """
        MVP11-T05: Generate candidates based on homeostasis state.
        
        When homeostasis dimensions are stressed (below setpoint by threshold),
        generate recovery candidates:
        - rest/recover: when energy is low
        - simplify_plan: when certainty is low (not compute_pressure)
        - seek_info: when certainty is low
        - defer_high_risk: when safety is low (not risk_exposure)
        
        Args:
            homeostasis_manager: HomeostasisManager instance
            stress_threshold: Threshold for considering a dimension stressed
        
        Returns:
            List of added homeostasis candidates
        """
        if not ENABLE_HOMEOSTASIS:
            return []
        
        added_candidates = []
        state = homeostasis_manager.state
        deviation = homeostasis_manager.get_deviation()
        
        # Energy low → rest/recover candidate
        if deviation.get("energy", 0) < -stress_threshold:
            candidate = Candidate(
                id="hs_rest",
                source="homeostasis",
                type=CandidateType.REST,
                utility=0.7,  # High utility for recovery
                risk=0.1,
                cost=0.2,
                rationale=f"Energy low ({state.energy:.2f}), need rest/recovery",
                payload={
                    "focus": "rest",
                    "dimension": "energy",
                    "current_value": state.energy,
                    "deviation": deviation.get("energy", 0)
                }
            )
            if self.add(candidate):
                added_candidates.append(candidate)
        
        # Certainty low → simplify_plan candidate
        if deviation.get("certainty", 0) < -stress_threshold:
            candidate = Candidate(
                id="hs_simplify",
                source="homeostasis",
                type=CandidateType.SIMPLIFY,
                utility=0.6,
                risk=0.2,
                cost=0.15,
                rationale=f"Certainty low ({state.certainty:.2f}), simplify plan",
                payload={
                    "focus": "simplify_plan",
                    "dimension": "certainty",
                    "current_value": state.certainty,
                    "deviation": deviation.get("certainty", 0)
                }
            )
            if self.add(candidate):
                added_candidates.append(candidate)
        
        # Certainty low → seek_info candidate
        if deviation.get("certainty", 0) < -stress_threshold:
            candidate = Candidate(
                id="hs_seek_info",
                source="homeostasis",
                type=CandidateType.INFO_SEEK,
                utility=0.65,
                risk=0.15,
                cost=0.25,
                rationale=f"Certainty low ({state.certainty:.2f}), seek more information",
                payload={
                    "focus": "seek_info",
                    "dimension": "certainty",
                    "current_value": state.certainty,
                    "deviation": deviation.get("certainty", 0)
                }
            )
            if self.add(candidate):
                added_candidates.append(candidate)
        
        # Safety low → defer_high_risk candidate
        if deviation.get("safety", 0) < -stress_threshold:
            candidate = Candidate(
                id="hs_defer",
                source="homeostasis",
                type=CandidateType.DEFER,
                utility=0.55,
                risk=0.1,
                cost=0.1,
                rationale=f"Safety low ({state.safety:.2f}), defer high-risk actions",
                payload={
                    "focus": "defer_high_risk",
                    "dimension": "safety",
                    "current_value": state.safety,
                    "deviation": deviation.get("safety", 0)
                }
            )
            if self.add(candidate):
                added_candidates.append(candidate)
        
        return added_candidates
    
    def clear(self) -> None:
        """Clear all candidates."""
        self.candidates = []
        self._id_set = set()
    
    def __len__(self) -> int:
        return len(self.candidates)
    
    def __iter__(self):
        return iter(self.candidates)
    
    def __getitem__(self, index: int) -> Candidate:
        return self.candidates[index]
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "candidates": [c.to_dict() for c in self.candidates],
            "max_size": self.max_size,
            "count": len(self.candidates),
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CandidatePool":
        """Deserialize from dictionary."""
        candidates = [Candidate.from_dict(c) for c in data.get("candidates", [])]
        return cls(
            candidates=candidates,
            max_size=data.get("max_size", 100),
        )


@dataclass
class ArbitrationResult:
    """Result of workspace arbitration."""
    chosen_focus: str
    chosen_candidate: Optional[Candidate]
    rationale: str
    tick_id: int
    ts: float = field(default_factory=time.time)
    all_candidates_count: int = 0
    broadcast_blocked: bool = False
    # MVP11-T05: Log homeostasis state in arbitration result
    homeostasis_state: Optional[Dict[str, float]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "chosen_focus": self.chosen_focus,
            "chosen_candidate": self.chosen_candidate.to_dict() if self.chosen_candidate else None,
            "rationale": self.rationale,
            "tick_id": self.tick_id,
            "ts": self.ts,
            "all_candidates_count": self.all_candidates_count,
            "broadcast_blocked": self.broadcast_blocked,
            "homeostasis_state": self.homeostasis_state,
        }


class Arbitrator:
    """
    T05: Workspace Arbitrator.
    
    Selects a single chosen_focus from candidates each tick.
    Applies HOT influence and intervention rules.
    
    Key behaviors:
    - Only one chosen_focus per tick
    - Writes rationale for selection
    - Broadcast mechanism for cross-module access
    - Intervention support (disable_broadcast)
    
    MVP11-T05: Homeostasis integration
    - Include homeostasis signal in scoring
    - Log homeostasis_state in result
    """
    
    def __init__(self, max_candidates: int = 100):
        """
        Initialize Arbitrator.
        
        Args:
            max_candidates: Maximum candidates to consider
        """
        self.max_candidates = max_candidates
        self.pool = CandidatePool(max_size=max_candidates)
        self._tick_id: int = 0
        self._last_result: Optional[ArbitrationResult] = None
        self._result_history: List[ArbitrationResult] = []
        self._broadcast_enabled: bool = True
        self._intervention_manager = None
        # MVP11-T05: Homeostasis manager reference
        self._homeostasis_manager: Optional[HomeostasisManager] = None
    
    def set_intervention_manager(self, manager) -> None:
        """
        Set intervention manager for checking disable_broadcast.
        
        Args:
            manager: InterventionManager instance
        """
        self._intervention_manager = manager
    
    def set_broadcast_enabled(self, enabled: bool) -> None:
        """
        Enable or disable broadcast.
        
        Args:
            enabled: Whether broadcast is enabled
        """
        self._broadcast_enabled = enabled
    
    def set_homeostasis_manager(self, manager: HomeostasisManager) -> None:
        """
        MVP11-T05: Set homeostasis manager for signal integration.
        
        Args:
            manager: HomeostasisManager instance
        """
        self._homeostasis_manager = manager
    
    def is_broadcast_disabled(self) -> bool:
        """
        Check if broadcast is disabled.
        
        Returns:
            True if broadcast is disabled
        """
        # Check intervention manager first
        if self._intervention_manager:
            if self._intervention_manager.is_broadcast_disabled():
                return True
        
        # Check local flag
        return not self._broadcast_enabled
    
    def add_candidate(self, candidate: Candidate) -> bool:
        """
        Add a candidate for arbitration.
        
        Args:
            candidate: Candidate to add
        
        Returns:
            True if added successfully
        """
        # If broadcast is disabled, candidates from external sources are blocked
        if self.is_broadcast_disabled() and candidate.source != "local":
            return False
        
        return self.pool.add(candidate)
    
    def add_candidates(self, candidates: List[Candidate]) -> int:
        """
        Add multiple candidates.
        
        Args:
            candidates: List of candidates to add
        
        Returns:
            Number of candidates added
        """
        added = 0
        for c in candidates:
            if self.add_candidate(c):
                added += 1
        return added
    
    def _compute_homeostasis_modifier(
        self,
        candidate: Candidate,
        homeostasis_signal: Optional[Dict]
    ) -> float:
        """
        MVP11-T05: Compute score modifier based on homeostasis signal.
        
        Rules:
        - If energy is low, boost rest/recovery candidates
        - If certainty is low, boost simplify/seek_info candidates
        - If safety is low, boost defer candidates
        
        Args:
            candidate: Candidate to evaluate
            homeostasis_signal: Signal from HomeostasisManager
        
        Returns:
            Score modifier (positive or negative)
        """
        if not homeostasis_signal or not ENABLE_HOMEOSTASIS:
            return 0.0
        
        modifier = 0.0
        stressed_dims = homeostasis_signal.get("stressed_dimensions", [])
        
        # Build lookup of stressed dimensions
        stressed_lookup = {d["dimension"]: d for d in stressed_dims}
        
        # Energy stressed → boost REST candidates
        if "energy" in stressed_lookup and candidate.type == CandidateType.REST:
            modifier += 0.15
        
        # Certainty stressed → boost SIMPLIFY and INFO_SEEK candidates
        if "certainty" in stressed_lookup:
            if candidate.type == CandidateType.SIMPLIFY:
                modifier += 0.12
            elif candidate.type == CandidateType.INFO_SEEK:
                modifier += 0.10
        
        # Safety stressed → boost DEFER candidates
        if "safety" in stressed_lookup and candidate.type == CandidateType.DEFER:
            modifier += 0.15
        
        return modifier
    
    def select_focus(
        self,
        tick_id: int,
        hot_modifiers: Optional[Dict[str, Any]] = None,
        intervention_manager=None,
    ) -> ArbitrationResult:
        """
        Select a single focus from candidates.
        
        This is the main arbitration method. It:
        1. Adds homeostasis-driven candidates (if enabled)
        2. Sorts candidates by score
        3. Applies HOT modifiers if provided
        4. Applies homeostasis modifiers
        5. Selects the best candidate
        6. Records rationale
        
        Args:
            tick_id: Current tick ID
            hot_modifiers: HOT influence (conflict_bias, control_penalty, etc.)
            intervention_manager: Optional intervention manager
        
        Returns:
            ArbitrationResult with chosen focus
        """
        self._tick_id = tick_id
        
        # Update intervention manager reference
        if intervention_manager:
            self._intervention_manager = intervention_manager
        
        broadcast_blocked = self.is_broadcast_disabled()
        
        # MVP11-T05: Get homeostasis signal and add candidates
        homeostasis_signal = None
        homeostasis_state_dict = None
        
        if ENABLE_HOMEOSTASIS and self._homeostasis_manager:
            homeostasis_signal = self._homeostasis_manager.signal()
            homeostasis_state_dict = self._homeostasis_manager.state.to_dict()
            
            # Add homeostasis-driven candidates to pool
            self.pool.add_homeostasis_candidates(self._homeostasis_manager)
        
        # If no candidates, return default
        if not self.pool.candidates:
            result = ArbitrationResult(
                chosen_focus="default_explore",
                chosen_candidate=None,
                rationale="No candidates available, defaulting to exploration",
                tick_id=tick_id,
                all_candidates_count=0,
                broadcast_blocked=broadcast_blocked,
                homeostasis_state=homeostasis_state_dict,
            )
            self._last_result = result
            self._result_history.append(result)
            return result
        
        # Sort candidates by base score
        self.pool.sort(reverse=True)
        
        # Apply HOT modifiers and homeostasis modifiers to scores
        candidates_with_modified_scores = []
        for c in self.pool.candidates:
            modified_score = c.compute_score()
            rationale_parts = [f"base_score={modified_score:.3f}"]
            
            # Apply conflict bias (HOT)
            if hot_modifiers:
                conflict_bias = hot_modifiers.get("conflict_bias", 0.0)
                control_penalty = hot_modifiers.get("control_penalty", 0.0)
                
                # Conflict bias: favor reflection/info_seek
                if c.type in (CandidateType.REFLECTION, CandidateType.INFO_SEEK):
                    modified_score += conflict_bias
                    rationale_parts.append(f"conflict_bias=+{conflict_bias:.3f}")
                
                # Control penalty: reduce risky candidates
                if c.risk > 0.5:
                    modified_score -= control_penalty
                    rationale_parts.append(f"control_penalty=-{control_penalty:.3f}")
            
            # MVP11-T05: Apply homeostasis modifiers
            if ENABLE_HOMEOSTASIS and homeostasis_signal:
                hs_modifier = self._compute_homeostasis_modifier(c, homeostasis_signal)
                if hs_modifier != 0:
                    modified_score += hs_modifier
                    rationale_parts.append(f"homeostasis=+{hs_modifier:.3f}")
            
            candidates_with_modified_scores.append((c, modified_score, rationale_parts))
        
        # Select best candidate
        best_candidate, best_score, rationale_parts = max(
            candidates_with_modified_scores,
            key=lambda x: x[1]
        )
        
        # Build rationale
        rationale = " | ".join(rationale_parts)
        rationale += f" | selected={best_candidate.id} from {len(self.pool.candidates)} candidates"
        
        # MVP11-T05: Add homeostasis urgency to rationale if applicable
        if homeostasis_signal and homeostasis_signal.get("urgency", 0) > 0:
            rationale += f" | hs_urgency={homeostasis_signal['urgency']:.3f}"
        
        # Extract focus
        chosen_focus = best_candidate.payload.get("focus", best_candidate.id)
        
        # Create result
        result = ArbitrationResult(
            chosen_focus=chosen_focus,
            chosen_candidate=best_candidate,
            rationale=rationale,
            tick_id=tick_id,
            all_candidates_count=len(self.pool.candidates),
            broadcast_blocked=broadcast_blocked,
            homeostasis_state=homeostasis_state_dict,
        )
        
        self._last_result = result
        self._result_history.append(result)
        
        # Clear pool for next tick
        self.pool.clear()
        
        return result
    
    def get_last_result(self) -> Optional[ArbitrationResult]:
        """Get the last arbitration result."""
        return self._last_result
    
    def get_result_history(self) -> List[ArbitrationResult]:
        """Get all arbitration results."""
        return self._result_history.copy()
    
    def clear_history(self) -> None:
        """Clear result history."""
        self._result_history = []
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "tick_id": self._tick_id,
            "pool": self.pool.to_dict(),
            "last_result": self._last_result.to_dict() if self._last_result else None,
            "history_count": len(self._result_history),
            "broadcast_enabled": self._broadcast_enabled,
            "homeostasis_enabled": ENABLE_HOMEOSTASIS,
        }


def create_candidate(
    source: str,
    candidate_type: str,
    utility: float = 0.5,
    risk: float = 0.0,
    cost: float = 0.0,
    rationale: str = "",
    payload: Optional[Dict[str, Any]] = None,
) -> Candidate:
    """
    Factory function to create a candidate.
    
    Args:
        source: Source module
        candidate_type: Type string
        utility: Utility score
        risk: Risk level
        cost: Cost estimate
        rationale: Explanation
        payload: Additional data
    
    Returns:
        Candidate instance
    """
    return Candidate(
        id="",
        source=source,
        type=CandidateType(candidate_type),
        utility=utility,
        risk=risk,
        cost=cost,
        rationale=rationale,
        payload=payload or {},
    )
